# Generated by Django 6.1.1 on 2026-09-21 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_feepayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='feepayment',
            name='receipt',
            field=models.FileField(blank=True, null=True, upload_to='receipts/'),
        ),
    ]
