# Generated by Django 6.1.1 on 2026-09-28 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_course_rename_employee_id_employee_employee_no_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='employee_no',
            new_name='employee_id',
        ),
    ]
