# Generated by Django 6.1.1 on 2026-09-28 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_rename_employee_no_employee_employee_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='employee_id',
            new_name='employee_no',
        ),
    ]
